config/routes.rb
MyApp::Application.routes.draw do

    get "password_resets/create"
    get "password_resets/edit"
    get "password_resets/update"
    get "reservations/finalisation"
    get "reservations/joujou"
    get "invitations/search"
  
    resources :profils
    resources :mailgenerals
    resources :offres
    resources :pagemembres
    resources :pageinvitations 
    resources :webmasters
    resources :reservations 
    resources :detailresas
    resources :welcome
    resources :password_resets
    resources :charges
    resources :partenaires
    resources :multidates
    resources :pagesystemes
 
 

    resources :authors do
    resources :commentaires
    resources :reservations 
    resources :paiments
 end

 resources :invitations do

     resources :multidates

   end

   resources :author_sessions, only: [ :new, :create, :destroy ]

   get 'login'  => 'author_sessions#new'
   get 'logout' => 'author_sessions#destroy'
  
  get "pages/forgot_password"
  get "pages/code_errone"
  get "pages/nondisponible"
  get "pages/contact"
  get "pages/fonctionnement"
  get "pages/limite"
  get "pages/confirmation"
  get "pages/epuise"
  get "welcome/index"
  get "welcome/help"
  get "welcome/inscription"

  get "webmasters/statut"

  root 'welcome#index'

  

end

app/models/author.rb
class Author < ActiveRecord::Base

  attr_accessible :username, :email, :avatar, :nom, :prenom, :password, :password_confirmation, :sexe, :nom_resa, :limite, :ville, :date_naissance

  validates :email,  presence: true, length: { minimum: 4, maximum: 15 } 

  validates :password,  presence: true, length: { minimum: 5,maximum: 12 } 

  validates :nom,  presence: true

  validates :prenom,  presence: true


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :username, presence: true, format: { with: VALID_EMAIL_REGEX },uniqueness: {case_sensitive: false}

  before_save { self.username = username.downcase }

  before_create :generate_token

  protected


   def generate_token
    self.token = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless Author.exists?(token: random_token)
    end
  end


  


  authenticates_with_sorcery!
   has_many :commentaires
   has_many :invitations
   has_many :reservations
   has_many :paiments
   validates_confirmation_of :password, message: "should match confirmation", if: :password
   
has_attached_file :avatar,
  :content_type => :image,
  :storage => :s3, 
  :bucket => 'julienwat75', 
  :s3_credentials => "#{Rails.root}/config/s3.yml",
  :url => "tunes/:style/:id/:filename",
  :path => "tunes/:style/:id/:filename"
   


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :author
end

app/models/commentaire.rb
class Commentaire < ActiveRecord::Base
  belongs_to :author
end

app/models/detailresa.rb
class Detailresa < ActiveRecord::Base
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base



attr_accessible :validation, :titre, :description, :avatar, :dateinvitation, :place, :vraiadresse;


belongs_to :author
has_many :reservations
has_many :multidates

has_attached_file :avatar,
  :content_type => :image, 
  :storage => :s3, 
  :bucket => 'julienwat75', 
  :s3_credentials => "#{Rails.root}/config/s3.yml",
  :url => "tunes/:style/:id/:filename",
  :path => "tunes/:style/:id/:filename"
  

  def self.aleatoire
  
    1000 + rand(5000) 
    
  end

  def self.late(dates)
    DateTime.now < dates
  end

def self.late2(dates)
    DateTime.now > dates
  end

   

end

app/models/mailgeneral.rb
class Mailgeneral < ActiveRecord::Base


	attr_accessible :titre, :body, :envoigeneral, :maildestinataire, :type_mail

end

app/models/multidate.rb
class Multidate < ActiveRecord::Base

	belongs_to :invitation

end

app/models/offre.rb
class Offre < ActiveRecord::Base
end

app/models/pageinvitation.rb
class Pageinvitation < ActiveRecord::Base
end

app/models/pagemembre.rb
class Pagemembre < ActiveRecord::Base
end

app/models/pagesysteme.rb
class Pagesysteme < ActiveRecord::Base
end

app/models/paiment.rb
class Paiment < ActiveRecord::Base

belongs_to :author	
end

app/models/partenaire.rb
class Partenaire < ActiveRecord::Base
end

app/models/profil.rb
class Profil < ActiveRecord::Base
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

belongs_to :invitation

attr_accessible :nombreinvitations,:pseudo

def self.late(dates)
    DateTime.now < dates
  end


end

app/models/sas.rb
class Sas < ActiveRecord::Base
end

app/models/webmaster.rb
class Webmaster < ActiveRecord::Base
end

app/controllers/partenaires_controller.rb
class PartenairesController < ApplicationController


	def index
      
      @partenaires=Partenaire.all

     
	end

	def new

	 @partenaires=Partenaire.new	


	end


	def show

	@partenaire = Partenaire.find(params[:id]) 	


	end




	def create


	@partenaires = Partenaire.new(profil_params)
    @partenaires.nom = params[:partenaire][:nom] 
    @partenaires.email = params[:partenaire][:email]
    @partenaires.adresse = params[:partenaire][:adresse] 
    @partenaires.ville = params[:partenaire][:ville] 
    @partenaires.telephone = params[:partenaire][:telephone] 
 
 

    @partenaires.save   #on sauvegarde
    redirect_to pageinvitations_path     # redirection vers l'index





	end


	def edit

      @partenaire = Partenaire.find(params[:id]) 	
    end


    def destroy

    @partenaire = Partenaire.find(params[:id]) 	

    @partenaire.destroy
    respond_to do |format|
      format.html { redirect_to partenaires_url }
      format.json { head :no_content }
    end
  end


  def update
    @partenaire = Partenaire.find(params[:id]) 	
   nom = params[:partenaire][:nom]
   email= params[:partenaire][:email]
 
    adresse= params[:partenaire][:adresse]
    telephone= params[:partenaire][:telephone]
 
 

    respond_to do |format|
      if @partenaire
         @partenaire.update_attribute(:nom, nom)
         @partenaire.update_attribute(:email, email)
         @partenaire.update_attribute(:adresse, adresse)
         @partenaire.update_attribute(:telephone, telephone)
  
 
 
        format.html { redirect_to partenaires_path, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @partenaire.errors, status: :unprocessable_entity }
      end
    end
  end



	def partenaire_params
    params.require(:partenaire).permit(:nom,:email,:adresse,:telephone)
  end


  def profil_params
    params.require(:partenaire).permit(:nom,:email,:adresse,:telephone)
  end






end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/offres_helper.rb
module OffresHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/partenaires_helper.rb
module PartenairesHelper
end

app/views/partenaires/_form.html.erb
<% provide(:title, "Ajouter un partenaire") %>


<div class="row" >

  <div   class="col-xs-0 col-md-4 col-lg-4 " > </div>


<!--  -----------------------------  Pour Mobile  --------------------------------------------------- -->


  <div   class="col-lg-12 col-lg-4 " >

<%= form_for(@partenaire) do |f| %>
  <ul>
  <% @partenaire.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <div class="field" style="color:black;">
    <%= f.label :nom %><br>
    <%= f.text_field :nom %>
  </div>

  <br><br>


  <div class="field" style="color:black;">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <br><br>

  <div class="field" style="color:black;">
    <%= f.label :adresse %><br>
    <%= f.text_field :adresse %>
  </div>

  <br><br>

  <div class="field" style="color:black;">
    <%= f.label :telephone %><br>
    <%= f.text_field :telephone %>
  </div>

  <br><br>




  <%= f.submit "valider" , :class => "grosbouton" %>
  



  <% end %>

</div>



  <div   class="col-xs-0 col-md-4 col-lg-4 " > </div>


</div>

app/views/partenaires/edit.html.erb
<%= render 'form' %>

app/views/partenaires/index.html.erb
<% provide(:title, "Partenaires") %>


<div class="row" >

  <div   class="col-xs-0 col-md-4 col-lg-4 " > </div>


<!--  -----------------------------  Pour Mobile  --------------------------------------------------- -->


  <div   class="col-lg-12 col-lg-4 " >


  <% @partenaires.each do |t| %>

      <p>    
      
       
        <%= t.nom %>
       
        <%= link_to 'Show', t %>
        
      </p>
     
    <% end %>
  

<br>

<%= link_to 'New partenaire', new_partenaire_path %>

  </div>


  <div   class="col-xs-0 col-md-4 col-lg-4 " > </div>


</div>

  

app/views/partenaires/new.html.erb
<% provide(:title, "Ajouter un partenaire") %>


<div class="row" >

  <div   class="col-xs-0 col-md-4 col-lg-4 " > </div>


<!--  -----------------------------  Pour Mobile  --------------------------------------------------- -->


  <div   class="col-lg-12 col-lg-4 " >

<%= form_for(@partenaires) do |f| %>
  <ul>
  <% @partenaires.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <div class="field" style="color:black;">
    <%= f.label :nom %><br>
    <%= f.text_field :nom %>
  </div>

  <br><br>


  <div class="field" style="color:black;">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <br><br>

  <div class="field" style="color:black;">
    <%= f.label :adresse %><br>
    <%= f.text_field :adresse %>
  </div>

  <br><br>

  <div class="field" style="color:black;">
    <%= f.label :telephone %><br>
    <%= f.text_field :telephone %>
  </div>

  <br><br>




  <%= f.submit "valider" , :class => "grosbouton" %>
  



  <% end %>

</div>



  <div   class="col-xs-0 col-md-4 col-lg-4 " > </div>


</div>

app/views/partenaires/show.html.erb
<% provide(:title, "Détail Partenaire") %>




<div class="row" >

  <div   class="col-xs-0 col-md-4 col-lg-4 " > </div>


<!--  -----------------------------  Pour PC  --------------------------------------------------- -->


  <div   class="col-xs-12 col-md-4 col-lg-4  hidden-xs" >




 

				        <div class="monecriture">
				          <strong>Nom:</strong>
				          <%= @partenaire.nom %>
				        </div>


				       <div class="monecriture">
				          <strong>Email:</strong>
				          <%= @partenaire.email %>
				        </div>

				        <div class="monecriture">
				          <strong>Adresse:</strong>
				          <%= @partenaire.adresse %>
				        </div>

				        <div class="monecriture">
				          <strong>Ville:</strong>
				          <%= @partenaire.ville %>
				        </div>

				         <div class="monecriture">
				          <strong>Téléphone:</strong>
				          <%= @partenaire.telephone %>
				        </div>

				        


				        <div class="monecriture">

				        <%= link_to 'Modifier ce compte', edit_partenaire_path(@partenaire) %> 

				        </div>
				        <div class="monecriture">

				         <%= link_to 'Supprimer ce compte', @partenaire, method: :delete, data: { confirm: 'Etes vous sur de vouloir supprimer ce compte?' } %>
				        </div>


      </div>



      <div   class="col-xs-0 col-md-4 col-lg-4 " > </div>



  </div>


      <!--  ------------------------------------------------------------------------------------------------------------  -->

      <!--  -----------------------------  Pour Mobile  --------------------------------------------------- -->


  <div   class="col-xs-12 col-md-4 col-lg-4  hidden-md hidden-lg"   >





   
         <div class="invitation" style="border-radius:5px 5px 5px 5px;padding:15px;">






         <div class="monecriture">
          <strong>Nom:</strong>
          <%= @partenaire.nom %>
        </div>


       <div class="monecriture">
          <strong>Email:</strong>
          <%= @partenaire.email %>
        </div>

        <div class="monecriture">
          <strong>Adresse:</strong>
          <%= @partenaire.adresse %>
        </div>

        <div class="monecriture">
          <strong>Ville:</strong>
          <%= @partenaire.ville %>
        </div>

         <div class="monecriture">
          <strong>Téléphone:</strong>
          <%= @partenaire.telephone %>
        </div>

        




        <div class="monecriture">

        <%= link_to 'Modifier ce compte', edit_partenaire_path(@partenaire) %> 

        </div>
        <div class="monecriture">

         <%= link_to 'Supprimer mon compte', @partenaire, method: :delete, data: { confirm: 'Etes vous sur de vouloir supprimer ce compte?' } %>
        </div>






      </div>


      </div>

      <!--  ------------------------------------------------------------------------------------------------------------  -->

      