config/routes.rb
MyApp::Application.routes.draw do

    get "password_resets/create"
    get "password_resets/edit"
    get "password_resets/update"
    get "reservations/finalisation"
    get "reservations/joujou"
    get "invitations/search"
  
    resources :profils
    resources :mailgenerals
    resources :offres
    resources :pagemembres
    resources :pageinvitations 
    resources :webmasters
    resources :reservations 
    resources :detailresas
    resources :welcome
    resources :password_resets
    resources :charges
    resources :partenaires
    resources :multidates
    resources :pagesystemes
 
 

    resources :authors do
    resources :commentaires
    resources :reservations 
    resources :paiments
 end

 resources :invitations do

     resources :multidates

   end

   resources :author_sessions, only: [ :new, :create, :destroy ]

   get 'login'  => 'author_sessions#new'
   get 'logout' => 'author_sessions#destroy'
  
  get "pages/forgot_password"
  get "pages/code_errone"
  get "pages/nondisponible"
  get "pages/contact"
  get "pages/fonctionnement"
  get "pages/limite"
  get "pages/confirmation"
  get "pages/epuise"
  get "welcome/index"
  get "welcome/help"
  get "welcome/inscription"

  get "webmasters/statut"

  root 'welcome#index'

  

end

app/models/author.rb
class Author < ActiveRecord::Base

  attr_accessible :username, :email, :avatar, :nom, :prenom, :password, :password_confirmation, :sexe, :nom_resa, :limite, :ville, :date_naissance

  validates :email,  presence: true, length: { minimum: 4, maximum: 15 } 

  validates :password,  presence: true, length: { minimum: 5,maximum: 12 } 

  validates :nom,  presence: true

  validates :prenom,  presence: true


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :username, presence: true, format: { with: VALID_EMAIL_REGEX },uniqueness: {case_sensitive: false}

  before_save { self.username = username.downcase }

  before_create :generate_token

  protected


   def generate_token
    self.token = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless Author.exists?(token: random_token)
    end
  end


  


  authenticates_with_sorcery!
   has_many :commentaires
   has_many :invitations
   has_many :reservations
   has_many :paiments
   validates_confirmation_of :password, message: "should match confirmation", if: :password
   
has_attached_file :avatar,
  :content_type => :image,
  :storage => :s3, 
  :bucket => 'julienwat75', 
  :s3_credentials => "#{Rails.root}/config/s3.yml",
  :url => "tunes/:style/:id/:filename",
  :path => "tunes/:style/:id/:filename"
   


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :author
end

app/models/commentaire.rb
class Commentaire < ActiveRecord::Base
  belongs_to :author
end

app/models/detailresa.rb
class Detailresa < ActiveRecord::Base
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base



attr_accessible :validation, :titre, :description, :avatar, :dateinvitation, :place, :vraiadresse;


belongs_to :author
has_many :reservations
has_many :multidates

has_attached_file :avatar,
  :content_type => :image, 
  :storage => :s3, 
  :bucket => 'julienwat75', 
  :s3_credentials => "#{Rails.root}/config/s3.yml",
  :url => "tunes/:style/:id/:filename",
  :path => "tunes/:style/:id/:filename"
  

  def self.aleatoire
  
    1000 + rand(5000) 
    
  end

  def self.late(dates)
    DateTime.now < dates
  end

def self.late2(dates)
    DateTime.now > dates
  end

   

end

app/models/mailgeneral.rb
class Mailgeneral < ActiveRecord::Base


	attr_accessible :titre, :body, :envoigeneral, :maildestinataire, :type_mail

end

app/models/multidate.rb
class Multidate < ActiveRecord::Base

	belongs_to :invitation

end

app/models/offre.rb
class Offre < ActiveRecord::Base
end

app/models/pageinvitation.rb
class Pageinvitation < ActiveRecord::Base
end

app/models/pagemembre.rb
class Pagemembre < ActiveRecord::Base
end

app/models/pagesysteme.rb
class Pagesysteme < ActiveRecord::Base
end

app/models/paiment.rb
class Paiment < ActiveRecord::Base

belongs_to :author	
end

app/models/partenaire.rb
class Partenaire < ActiveRecord::Base
end

app/models/profil.rb
class Profil < ActiveRecord::Base
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

belongs_to :invitation

attr_accessible :nombreinvitations,:pseudo

def self.late(dates)
    DateTime.now < dates
  end


end

app/models/sas.rb
class Sas < ActiveRecord::Base
end

app/models/webmaster.rb
class Webmaster < ActiveRecord::Base
end

app/controllers/pageinvitations_controller.rb
class PageinvitationsController < ApplicationController



  before_filter :zero_authors_or_authenticated 


  def zero_authors_or_authenticated
  unless Invitation.count == 0 || current_user
    redirect_to login_path
    return false
  end
end




def index

  @pagesysteme=Pagesysteme.find(1)

  limite_blackliste = 2


  unless  current_user && current_user.id == 3
   
   if @pagesysteme.ouverture_invitation == false || current_user.point_negatif >= limite_blackliste 
   redirect_to "/pages/nondisponible" 
   end

  end


a=0
@user=current_user
 #a=params[:id]
@page_suivante=a.to_i+1


#--------------------------------------- mise a jour validation --------------------------------------

@invitation1=Invitation.all


  @invitation1.each do |t| 

         if t.multidates.length > 0 && Invitation.late(t.multidates.order(:datex).last.datex) 



         

          else

          t.update_attribute(:validation, false)


         end 


 end

 #------------------------------------------------------------------------------------------------------       


  

@invitations2=Invitation.find(:all,
                     :conditions => {:validation => true},
                      :order      =>  "dateinvitation",
                      :limit      =>  20,
                       :offset      =>  a.to_i*20)     # numero de page qu on souhaite afficher


@comptage=Invitation.find(:all,
                     :conditions => {:validation => true})     # numero de page qu on souhaite afficher







calcul=@comptage.count.to_f/20
@nombre_pages=calcul.ceil



 

end





def show

   @pagesysteme=Pagesysteme.find(1)

  limite_blackliste = 2


  unless  current_user && current_user.id == 3
   
   if @pagesysteme.ouverture_invitation == false || current_user.point_negatif >= limite_blackliste 
   redirect_to "/pages/nondisponible" 
   end

  end

#a=1
@user=current_user
 a=params[:id]
@page_suivante=a.to_i+1


#--------------------------------------- mise a jour validation --------------------------------------

@invitation1=Invitation.all


  @invitation1.each do |t| 

         if t.multidates.length > 0 && Invitation.late(t.multidates.order(:datex).last.datex) 



         

          else

          t.update_attribute(:validation, false)


         end 


 end

 #------------------------------------------------------------------------------------------------------       


  

@invitations2=Invitation.find(:all,
                     :conditions => {:validation => true,:validation => true},
                      :order      =>  "dateinvitation",
                      :limit      =>  20,
                       :offset      =>  a.to_i*20)     # numero de page qu on souhaite afficher

@comptage=Invitation.find(:all,
                     :conditions => {:validation => true})     # numero de page qu on souhaite afficher




calcul=@comptage.count.to_f/20
@nombre_pages=calcul.ceil

 

  end






end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/offres_helper.rb
module OffresHelper
end

app/helpers/pageinvitations_helper.rb
module PageinvitationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/pageinvitations/Nouveau dossier/show.html.erb
<%= link_to "Ajouter une proposition", new_invitation_path, class: "button" %>



<% @invitations2.each do |t| %>

<% if t.validation  %>

<p> 
<b><%= t.titre  %></b>, <%= t.description  %>,<%= t.dateinvitation  %>,<%= t.author_id %>
<%= link_to 'Show', t %>
</p>

<p>
<% var=t.avatar.url %>
<% var[0,23] = "https://s3-eu-west-1.amazonaws.com" %>
</p>

<img src="<%= var %>" alt="arobas" style="width:164px; height:164px;" />

<% end %>

<%  end  %>

<br>


<% page=0  %>

<% while page<10 %>



 
<a href="/pageinvitations/<%= page %>">  <%= page+1 %> </a> 


 <% page+=1 %>
 <% end %>
 

app/views/pageinvitations/_invitations.html.erb
<% provide(:title, "Invitations Gratuites") %>
 






<!-- ------------------------------------------------------------------------------------   -->

        

<div class="row "  >

                
        <% @invitations2.each do |t| %>

          <% if true %>


        <!--  switch et variable --> 

        <% jour=t.multidates.order(:datex).last.datex.strftime("%A") %>  

  <% mois=t.multidates.order(:datex).last.datex.strftime("%B")  %>

<% case jour  %>
 <% when "Monday"  %>
 <%  jour= "Lundi" %> 
 <% when "Tuesday"  %>
 <%  jour= "Mardi" %> 
<% when "Wednesday"  %>
 <%  jour= "Mercredi" %>
  <% when "Thursday"  %>
 <%  jour= "Jeudi" %>
  <% when "Friday"  %>
 <%  jour= "Vendredi" %>
  <% when "Saturday"  %>
 <%  jour= "Samedi" %> 
  <% when "Sunday"  %>
 <%  jour= "Dimanche" %> 
<% else  %>              
 <% puts 'Only single-digit numbers are allowed' %>
 <% end %>

 <% case mois  %>
 <% when "January"  %>
 <%  mois= "Janvier" %> 
 <% when "February"  %>
 <%  mois= "Février" %> 
<% when "March"  %>
 <%  mois= "Mars" %>
  <% when "April"  %>
 <%  mois= "Avril" %>
  <% when "May"  %>
 <%  mois= "Mai" %>
  <% when "June"  %>
 <%  mois= "Juin" %>
  <% when "July"  %>
 <%  mois= "Juillet" %>
  <% when "August"  %>
 <%  mois= "Aout" %>
  <% when "September"  %>
 <%  mois= "Septembre" %>
  <% when "October"  %>
 <%  mois= "Octobre" %>
   <% when "November"  %>
 <%  mois= "Novembre" %>
  <% when "December"  %>
 <%  mois= "Décembre" %>
<% else  %>              
 
 <% end %>


<% var=t.avatar.url %>

<% var[0,23] = "https://s3-eu-west-1.amazonaws.com" %>

<% resume=t.description %>
<% resume=resume[0...200]%>



 

   


        <!--  fin switch et variable -->

          

      
             <!--  -------------------------------- Invitations ---------------------------- --> 
               <div  class="col-xs-12  col-md-6 col-lg-4 hidden-md hidden-sm fondgris" style="text-align:left;height:400px;overflow:hidden;margin-bottom:10px;"    >  <!-- debut premier div ---- -->
                  <div  align="center">
                <!--  Version PC ------------------------------------------------------------------ -->
                <div  class=" " style=";margin-bottom:35px;border-radius:0px 0px 10px 10px;border-radius:5px 5px 0px 0px;border:1px solid rgba(0, 0, 0, 0.2);background:white; ">
                         <div style=""> 
                                   <a href="<%=  invitation_path(t.id) %>">  
                                   <div class="titre_vignette" style="font-family: Helvetica Neue,Arial,sans-serif;padding-left:10px;color: rgb(104, 104, 104);background:white;height:60px;text-align:left;"> 
                                    <span class="glyphicon glyphicon-star"></span> 
                                    <%=  t.titre %> 

                                                
                                    </div>
                                    </a>
                                    <div style="padding-left:10px;text-align:left;padding-bottom:10px;border-bottom:1px solid rgba(0, 0, 0, 0.2);">
                                                Actuellement 
                                      </div>     
                                     



                         </div>
                        


                          <a href="<%=  invitation_path(t.id) %>">
                             <div class="vignette" >

                                <div align="center >
                                    <a href="<%=  invitation_path(t.id) %>">
                                   <img src="<%= var %>" alt="arobas" style="height:300px;text-align:left;margin-right:10px;" />
                                 </div>
                                   </a>
                                         
                              </div>
                         
                              


                      </div>

                    </div>  
                     
                              
              </div>
                  <!-- Fin Version PC -------------------------------------------------  -->

                <!--  Version tablette --> 

                  <div  class="col-sm-12 col-md-6 hidden-xs hidden-sm  hidden-lg  fondgris" style="text-align:left;height:400px;overflow:hidden;margin-bottom:10px;"    >  <!-- debut premier div ---- -->
                  <div align="center">
                <!--  Version PC ------------------------------------------------------------------ -->
                <div  class=" " style=";margin-bottom:35px;border-radius:0px 0px 10px 10px;border-radius:5px 5px 0px 0px;border:1px solid rgba(0, 0, 0, 0.2);background:white; ">
                         <div style=""> 
                                   <a href="<%=  invitation_path(t.id) %>">  
                                   <div class="titre_vignette" style="font-family: Helvetica Neue,Arial,sans-serif;padding-left:10px;color: rgb(104, 104, 104);background:white;text-align:left;height:60px;"> 
                                    <span class="glyphicon glyphicon-star"></span> 
                                    <%=  t.titre %> 

                                                
                                    </div>
                                    </a>
                                    <div style="padding-left:10px;text-align:left;padding-bottom:10px;border-bottom:1px solid rgba(0, 0, 0, 0.2);">
                                               Actuellement 
                                      </div>     
                                     



                         </div>


                          <a href="<%=  invitation_path(t.id) %>">
                             <div class="vignette" >

                                <div align="center" >
                                    <a href="<%=  invitation_path(t.id) %>">
                                   <img src="<%= var %>" alt="arobas" style="height:300px;text-align:left;margin-right:10px;" />
                                 </div>
                                   </a>
                                         
                              </div>
                         
                              


                      </div>

                    </div>  
                     
                              
              </div> 

               
                     <!--  Fin version tablette -->

                       <!--  Version small --> 

                  <div  class="col-sm-6 hidden-xs hidden-md  hidden-lg fondgris" style="text-align:left;height:480px;overflow:hidden;margin-bottom:10px;"    >  <!-- debut premier div ---- -->
                  <div align="center">
                <!--  Version PC ------------------------------------------------------------------ -->
                <div  class=" " style=";margin-bottom:35px;border-radius:0px 0px 10px 10px;border-radius:5px 5px 0px 0px;border:1px solid rgba(0, 0, 0, 0.2);background:white; ">
                         <div style=""> 
                                   <a href="<%=  invitation_path(t.id) %>">  
                                   <div class="titre_vignette" style="font-family: Helvetica Neue,Arial,sans-serif;padding-left:10px;color: rgb(104, 104, 104);background:white;text-align:left;"> 
                                    <span class="glyphicon glyphicon-star"></span> 
                                    <%=  t.titre %> 

                                                
                                    </div>
                                    </a>
                                    <div style="padding-left:10px;text-align:left;padding-bottom:10px;">
                                               Actuellement 
                                      </div>     
                                     



                         </div>


                          <a href="<%=  invitation_path(t.id) %>">
                             <div class="vignette" >

                                <div align="center" >
                                    <a href="<%=  invitation_path(t.id) %>">
                                   <img src="<%= var %>" alt="arobas" style="height:300px;text-align:left;margin-right:10px;" />
                                 </div>
                                   </a>
                                         
                              </div>
                         
                              


                      </div>

                    </div>  
                     
                              
              </div> 

               
                     <!--  Fin version small -->





           <% else %>
   
          


           <% end %>  <!--  Fin du if  -->


      <% end %>

 </div>






<script type="text/javascript">
$('.carousel').carousel()

</script>


<!-- ---------------------------  Paging ---------------------------------- -->


 <div class="row" >


                  <div  class="col-xs-0 col-md-4 col-lg-4"></div> 
                         <div  class="col-xs-12 col-md-4 col-lg-4" style="margin-top:20px;color:white;font-size:20px;align:center;">


                                    <% page=0  %>


                                    <ul class="pagination">


                                  <% while page< @nombre_pages %>



                                   <li><a href="/pageinvitations/<%= page %>"><%= page+1 %></a></li>


                                     


                                   <% page+=1 %>

                                     <% end %>

                                     </ul>

                            </div>

                   <div  class="col-xs-0 col-md-4 col-lg-4"></div> 

    


      </div>   <!-- Fin du row  -->







<!-- Fin du paging -->


















  

app/views/pageinvitations/index.html.erb
<%= render 'invitations' %>

app/views/pageinvitations/show.html.erb
<%= render 'invitations' %>