config/routes.rb
MyApp::Application.routes.draw do

    get "password_resets/create"
    get "password_resets/edit"
    get "password_resets/update"
    get "reservations/finalisation"
    get "reservations/joujou"
    get "invitations/search"
  
    resources :profils
    resources :mailgenerals
    resources :offres
    resources :pagemembres
    resources :pageinvitations 
    resources :webmasters
    resources :reservations 
    resources :detailresas
    resources :welcome
    resources :password_resets
    resources :charges
    resources :partenaires
    resources :multidates
    resources :pagesystemes
 
 

    resources :authors do
    resources :commentaires
    resources :reservations 
    resources :paiments
 end

 resources :invitations do

     resources :multidates

   end

   resources :author_sessions, only: [ :new, :create, :destroy ]

   get 'login'  => 'author_sessions#new'
   get 'logout' => 'author_sessions#destroy'
  
  get "pages/forgot_password"
  get "pages/code_errone"
  get "pages/nondisponible"
  get "pages/contact"
  get "pages/fonctionnement"
  get "pages/limite"
  get "pages/confirmation"
  get "pages/epuise"
  get "welcome/index"
  get "welcome/help"
  get "welcome/inscription"

  get "webmasters/statut"

  root 'welcome#index'

  

end

app/models/author.rb
class Author < ActiveRecord::Base

  attr_accessible :username, :email, :avatar, :nom, :prenom, :password, :password_confirmation, :sexe, :nom_resa, :limite, :ville, :date_naissance

  validates :email,  presence: true, length: { minimum: 4, maximum: 15 } 

  validates :password,  presence: true, length: { minimum: 5,maximum: 12 } 

  validates :nom,  presence: true

  validates :prenom,  presence: true


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :username, presence: true, format: { with: VALID_EMAIL_REGEX },uniqueness: {case_sensitive: false}

  before_save { self.username = username.downcase }

  before_create :generate_token

  protected


   def generate_token
    self.token = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless Author.exists?(token: random_token)
    end
  end


  


  authenticates_with_sorcery!
   has_many :commentaires
   has_many :invitations
   has_many :reservations
   has_many :paiments
   validates_confirmation_of :password, message: "should match confirmation", if: :password
   
has_attached_file :avatar,
  :content_type => :image,
  :storage => :s3, 
  :bucket => 'julienwat75', 
  :s3_credentials => "#{Rails.root}/config/s3.yml",
  :url => "tunes/:style/:id/:filename",
  :path => "tunes/:style/:id/:filename"
   


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :author
end

app/models/commentaire.rb
class Commentaire < ActiveRecord::Base
  belongs_to :author
end

app/models/detailresa.rb
class Detailresa < ActiveRecord::Base
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base



attr_accessible :validation, :titre, :description, :avatar, :dateinvitation, :place, :vraiadresse;


belongs_to :author
has_many :reservations
has_many :multidates

has_attached_file :avatar,
  :content_type => :image, 
  :storage => :s3, 
  :bucket => 'julienwat75', 
  :s3_credentials => "#{Rails.root}/config/s3.yml",
  :url => "tunes/:style/:id/:filename",
  :path => "tunes/:style/:id/:filename"
  

  def self.aleatoire
  
    1000 + rand(5000) 
    
  end

  def self.late(dates)
    DateTime.now < dates
  end

def self.late2(dates)
    DateTime.now > dates
  end

   

end

app/models/mailgeneral.rb
class Mailgeneral < ActiveRecord::Base


	attr_accessible :titre, :body, :envoigeneral, :maildestinataire, :type_mail

end

app/models/multidate.rb
class Multidate < ActiveRecord::Base

	belongs_to :invitation

end

app/models/offre.rb
class Offre < ActiveRecord::Base
end

app/models/pageinvitation.rb
class Pageinvitation < ActiveRecord::Base
end

app/models/pagemembre.rb
class Pagemembre < ActiveRecord::Base
end

app/models/pagesysteme.rb
class Pagesysteme < ActiveRecord::Base
end

app/models/paiment.rb
class Paiment < ActiveRecord::Base

belongs_to :author	
end

app/models/partenaire.rb
class Partenaire < ActiveRecord::Base
end

app/models/profil.rb
class Profil < ActiveRecord::Base
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

belongs_to :invitation

attr_accessible :nombreinvitations,:pseudo

def self.late(dates)
    DateTime.now < dates
  end


end

app/models/sas.rb
class Sas < ActiveRecord::Base
end

app/models/webmaster.rb
class Webmaster < ActiveRecord::Base
end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController

 def new


  end

  def create
   if login(params[:username], params[:password])

       flash[:success] = "Welcome to billetgratuit.com "

       

      redirect_back_or_to(author_path(current_user.id))  
    else
      flash.now.alert = "Login failed."
      redirect_to "/welcome"
    end
  end

  def destroy

   

    logout
    redirect_to "/welcome"
   
  end


end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/offres_helper.rb
module OffresHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/author_sessions/new.html.erb
<% provide(:title, "Se connecter") %>

<div class="row " >

    <div class="col-xs-0 col-sm-4 col-md-4 col-lg-4 text-center " ></div>


     <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 text-center " >




                              <div style="margin-bottom:200px;">

                                     <h2 ><small><font color="white">Se connecter</font></small></h2><br>

                                    <%= form_tag author_sessions_path, method: :post do %>

                                    <div class="field">
                                    <%=  text_field_tag :username, "Email",:style =>'color:grey;width:100%;font-size:19px;' %>
                                    
                                   </div>

                                   <br>
                                  
                                  <div class="field">
                                    
                                   <%= password_field_tag :password, nil, placeholder: "Password" ,:style =>'padding:10px;color:grey;width:100%;font-size:19px;', :class => 'couleurnoir'   %>

                                  </div>

                                   <div style="margin:20px;"><a href="/pages/contact.html"> Mot de passe oublié?</a> </div>


                                    <div style="margin-top:20px;width:100%;"> 
                                      <%= submit_tag  "Se connecter", :class => 'btn btn-default btn-lg',:style =>'width:100%;'  %>
                                    </div>
                         
                               

                                   <% end %>

                                   <div style="margin-top:30px;margin-bottom:20px;"> Pas encore membre?</div>
                        

                                    
                                  <div style="margin-top:0px;width:100%;background:grey;"> 
                                    <%= link_to "S'inscrire", new_author_path,  :class=>"btn btn-inscription btn-lg",:style =>'color:white;' %>

                                  </div>
                          </div>






                   </div>

      <div class="col-xs-0 col-sm-4 col-md-4 col-lg-4 text-center " ></div>

 </div>     


           